Repository piro16knockknock/knockknock, pull requests merged in 2022-02, with the labels that each got.

#8 [FEAT] 집 정보 변경 & 등록 시 집 이름 중복 확인, 빈칸 경고
  apps/setting/views.py
  static/css/setting/myhome_detail.css
  templates/setting/myhome_detail.html
  templates/setting/myhome_form.html
Labels: fix

#10 [FEAT] 이전 집 생활 수칙 보기 & 가져오기
  apps/home/models.py
  apps/login/urls.py
  apps/login/views.py
  static/css/mypage/mypage_temp.css
  static/css/style.css
  templates/login/mypage_temp.html
  templates/setting/myhome_detail.html
Labels: enhancement

#12 [FEAT] 룸메이트 프로필 보기 / 넘기기 버튼
  static/css/setting/roommate_list.css
  templates/setting/roommate_list.html
Labels: enhancement

#14 [FEAT] 전세/월세 선택에 따라 월세 납부일 input 막기, 공과금 CRUD
  apps/setting/models.py
  apps/setting/views.py
  static/css/setting/myhome_detail.css
  static/css/setting/myhome_form.css
  static/css/setting/roommate_list.css
  static/css/style.css
  static/js/login/mypage_temp.js
  static/js/setting/myhome_detail.js
  static/js/setting/myhome_form.js
  static/js/setting/roommate_list.js
  templates/login/mypage_temp.html
  templates/setting/myhome_detail.html
  templates/setting/myhome_form.html
  templates/setting/roommate_list.html
Labels: enhancement, fix

#20 [FEAT] 룸메이트 칭호 표시
  apps/home/models.py
  apps/login/admin.py
  apps/login/models.py
  apps/login/views.py
  apps/setting/admin.py
  apps/setting/models.py
  apps/setting/views.py
  static/css/login/mypage.css
  static/css/mypage/mypage_temp.css
  static/css/style.css
  static/js/login/mypage.js
  static/js/setting/roommate_list.js
  templates/login/mypage.html
  templates/setting/roommate_list.html
Labels: enhancement, fix

#26 [FIX] 할 일 삭제하기 ajax 수정 및 카테고리 추가 redirect로 변경
  apps/home/views.py
  static/js/home/date_todo.js
  static/js/home/home_cate.js
  templates/home/date_todo/date_todo.html
Labels: fix, coworker
